# Generated by Django 2.2.4 on 2019-09-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attractions'),
        ),
    ]
