# Generated by Django 2.2.1 on 2019-07-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('adresses', '0001_initial'),
        ('attractions', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('descriptions', models.TextField(verbose_name='Descrição')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('adresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_spot.End', verbose_name='Endereço')),
                ('assessments', models.ManyToManyField(to='assessments.Assessments', verbose_name='Avaliações')),
                ('attractions', models.ManyToManyField(to='attractions.Attractions', verbose_name='Atrações')),
                ('comments', models.ManyToManyField(to='comments.Comments', verbose_name='Comentários')),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turístico',
                'ordering': ['name'],
            },
        ),
    ]
