# Generated by Django 2.2.4 on 2019-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spot', '0002_auto_20190718_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist-spot'),
        ),
    ]
