# Generated by Django 2.2.4 on 2019-09-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spot', '0003_touristspot_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='adresses',
            new_name='adresses',
        ),
    ]
